# Generated by Django 4.2.7 on 2026-05-06 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_view_orders', 'Can view production orders'), ('can_edit_orders', 'Can edit production orders'), ('can_delete_orders', 'Can delete production orders'), ('can_view_buckets', 'Can view production buckets'), ('can_edit_buckets', 'Can edit production buckets'), ('can_delete_buckets', 'Can delete production buckets'), ('can_view_heats', 'Can view heats'), ('can_edit_heats', 'Can edit heats'), ('can_delete_heats', 'Can delete heats'), ('can_view_lf', 'Can view LF pages'), ('can_control_lf', 'Can control LF operations'), ('can_record_temperature', 'Can record temperature'), ('can_record_analysis', 'Can record analysis'), ('can_add_alloys', 'Can add alloys'), ('can_confirm_alloys', 'Can confirm alloys'), ('can_view_eaf', 'Can view EAF pages'), ('can_control_eaf', 'Can control EAF operations'), ('can_view_ccm', 'Can view CCM pages'), ('can_control_ccm', 'Can control CCM operations'), ('can_view_quality', 'Can view quality data'), ('can_edit_quality', 'Can edit quality data'), ('can_view_reports', 'Can view reports'), ('can_export_reports', 'Can export reports'), ('can_manage_users', 'Can manage users'), ('can_view_audit_log', 'Can view audit logs')], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('production_manager', 'Production Manager'), ('production_planner', 'Production Planner'), ('lf_operator', 'LF Operator'), ('eaf_operator', 'EAF Operator'), ('ccm_operator', 'CCM Operator'), ('quality_engineer', 'Quality Engineer'), ('maintenance', 'Maintenance'), ('viewer', 'Viewer (Read Only)')], default='viewer', max_length=30, verbose_name='User Role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='accounts_user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('module', models.CharField(max_length=100)),
                ('details', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity Log',
                'verbose_name_plural': 'User Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
