# Generated by Django 4.2.7 on 2026-05-09 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0002_delete_orderheat'),
        ('lf', '0004_lfheat_bucket_lfheat_heat_sequence_lfheat_temp_max_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EAFElectricalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('STANDARD', 'Standard Profile'), ('FAST', 'Fast Melting'), ('ECONOMY', 'Economy Mode'), ('PRECISE', 'Precise Control')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('working_point_1', models.JSONField(default=dict, help_text='Voltage, Current, Tap Position')),
                ('working_point_2', models.JSONField(default=dict)),
                ('working_point_3', models.JSONField(default=dict)),
                ('working_point_4', models.JSONField(default=dict)),
                ('working_point_5', models.JSONField(default=dict)),
                ('working_point_6', models.JSONField(default=dict)),
                ('working_point_7', models.JSONField(default=dict)),
                ('working_point_8', models.JSONField(default=dict)),
                ('working_point_9', models.JSONField(default=dict)),
                ('working_point_10', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EAFHeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heat_number', models.IntegerField(unique=True, verbose_name='Heat Number')),
                ('furnace_id', models.IntegerField(default=1, verbose_name='Furnace ID')),
                ('heat_sequence', models.IntegerField(default=1, verbose_name='Heat Sequence in Bucket')),
                ('scrap_weight', models.FloatField(default=0, verbose_name='Scrap Weight (tons)')),
                ('dri_weight', models.FloatField(default=0, verbose_name='DRI Weight (tons)')),
                ('liquid_weight', models.FloatField(default=0, verbose_name='Liquid Steel Weight (tons)')),
                ('target_weight', models.FloatField(default=120, verbose_name='Target Weight (tons)')),
                ('temp_target', models.FloatField(default=1620, verbose_name='Target Temperature (°C)')),
                ('temp_min', models.FloatField(default=1600, verbose_name='Minimum Temperature (°C)')),
                ('temp_max', models.FloatField(default=1640, verbose_name='Maximum Temperature (°C)')),
                ('electrical_profile', models.CharField(default='STANDARD', max_length=50, verbose_name='Electrical Profile')),
                ('working_point', models.IntegerField(default=1, verbose_name='Working Point')),
                ('tap_position', models.IntegerField(default=1, verbose_name='Tap Position')),
                ('power_consumption', models.FloatField(default=0, verbose_name='Power Consumption (kWh/ton)')),
                ('electrode_position', models.FloatField(default=450, verbose_name='Electrode Position (mm)')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('charging', 'Charging'), ('melting', 'Melting'), ('refining', 'Refining'), ('tapping', 'Tapping'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20, verbose_name='Status')),
                ('current_phase', models.CharField(choices=[('preparation', 'Preparation'), ('charging', 'Charging'), ('melting', 'Melting'), ('foaming_slag', 'Foaming Slag'), ('refining', 'Refining'), ('tapping', 'Tapping')], default='preparation', max_length=20, verbose_name='Current Phase')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Start Time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='End Time')),
                ('phase_start_time', models.DateTimeField(blank=True, null=True, verbose_name='Current Phase Start Time')),
                ('operator_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Operator Name')),
                ('shift_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='Shift ID')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bucket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eaf_heats', to='production.productionbucket', verbose_name='Production Bucket')),
                ('steel_grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lf.steelgrade', verbose_name='Steel Grade')),
            ],
            options={
                'verbose_name': 'EAF Heat',
                'verbose_name_plural': 'EAF Heats',
                'ordering': ['-heat_number'],
            },
        ),
        migrations.CreateModel(
            name='EAFEnergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('power_active', models.FloatField(default=0, verbose_name='Active Power (MW)')),
                ('power_reactive', models.FloatField(default=0, verbose_name='Reactive Power (MVAR)')),
                ('energy_consumed', models.FloatField(default=0, verbose_name='Energy Consumed (MWh)')),
                ('electrode_position', models.FloatField(default=0, verbose_name='Electrode Position (mm)')),
                ('tap_position', models.IntegerField(default=1, verbose_name='Tap Position')),
                ('working_point', models.IntegerField(default=1, verbose_name='Working Point')),
                ('heat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_data', to='eaf.eafheat')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EAFDelay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('electrical', 'Electrical'), ('mechanical', 'Mechanical'), ('material', 'Material'), ('process', 'Process'), ('maintenance', 'Maintenance')], max_length=20)),
                ('code', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('cause', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(default=0, verbose_name='Duration (seconds)')),
                ('status', models.CharField(default='active', max_length=20)),
                ('heat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delays', to='eaf.eafheat')),
            ],
        ),
        migrations.CreateModel(
            name='EAFCharging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charging_type', models.CharField(choices=[('bucket', 'Bucket Charging'), ('continuous', 'Continuous Charging (DRI)')], max_length=20)),
                ('material', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('charging_time', models.DateTimeField(auto_now_add=True)),
                ('operator_name', models.CharField(blank=True, max_length=100)),
                ('heat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chargings', to='eaf.eafheat')),
            ],
        ),
        migrations.AddIndex(
            model_name='eafheat',
            index=models.Index(fields=['bucket', 'heat_sequence'], name='eaf_eafheat_bucket__443838_idx'),
        ),
        migrations.AddIndex(
            model_name='eafheat',
            index=models.Index(fields=['status'], name='eaf_eafheat_status_673da2_idx'),
        ),
    ]
