# Generated by Django 4.2.7 on 2026-05-29 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ['-created_at'], 'verbose_name': 'جلسه', 'verbose_name_plural': 'جلسات'},
        ),
        migrations.AddField(
            model_name='meeting',
            name='audio_duration',
            field=models.IntegerField(default=0, verbose_name='مدت زمان (ثانیه)'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meeting',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='key_points',
            field=models.JSONField(blank=True, default=list, verbose_name='نکات کلیدی'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='action_items',
            field=models.JSONField(blank=True, default=list, verbose_name='اقدامات'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio/%Y/%m/%d/', verbose_name='فایل صوتی'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='decisions',
            field=models.JSONField(blank=True, default=list, verbose_name='تصمیمات'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('processing', 'در حال پردازش'), ('transcribing', 'در حال تبدیل به متن'), ('summarizing', 'در حال خلاصه\u200cسازی'), ('completed', 'تکمیل شده'), ('failed', 'خطا')], default='pending', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='summary',
            field=models.TextField(blank=True, verbose_name='خلاصه جلسه'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان جلسه'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='transcription',
            field=models.TextField(blank=True, verbose_name='متن پیاده شده'),
        ),
    ]
