# Generated by Django 4.2.7 on 2026-04-26 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LFHeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heat_number', models.IntegerField(unique=True, verbose_name='شماره ذوب')),
                ('furnace_id', models.IntegerField(default=1, verbose_name='شناسه کوره')),
                ('liquid_weight', models.FloatField(default=0, verbose_name='وزن مذاب (تن)')),
                ('target_liquid_weight', models.FloatField(default=120, verbose_name='وزن هدف (تن)')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('running', 'در حال اجرا'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده'), ('ready_to_tap', 'آماده تخلیه')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('current_phase', models.CharField(choices=[('preparation', 'آماده سازی'), ('ladle_arrival', 'ورود پاتیل'), ('heating', 'گرمایش'), ('alloying', 'آلیاژسازی'), ('trimming', 'تنظیم نهایی'), ('holding', 'نگهداری'), ('tapping', 'تخلیه')], default='preparation', max_length=20, verbose_name='فاز جاری')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان')),
                ('phase_start_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع فاز جاری')),
                ('heating_power', models.FloatField(default=15, verbose_name='توان گرمایش (MW)')),
                ('argon_flow', models.FloatField(default=150, verbose_name='جریان آرگون (L/min)')),
                ('electrode_position', models.FloatField(default=450, verbose_name='موقعیت الکترود (mm)')),
                ('production_standard', models.CharField(default='LF_STD_FAST', max_length=50, verbose_name='استاندارد تولید')),
                ('operator_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام اپراتور')),
                ('shift_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='شناسه شیفت')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ذوب LF',
                'verbose_name_plural': 'ذوب\u200cهای LF',
                'ordering': ['-heat_number'],
            },
        ),
        migrations.CreateModel(
            name='SteelGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='کد فولاد')),
                ('name', models.CharField(max_length=100, verbose_name='نام فولاد')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('temp_min', models.FloatField(default=1570, verbose_name='حداقل دما (°C)')),
                ('temp_target', models.FloatField(default=1600, verbose_name='دمای هدف (°C)')),
                ('temp_max', models.FloatField(default=1620, verbose_name='حداکثر دما (°C)')),
                ('analysis_limits', models.JSONField(default=dict, verbose_name='محدوده آنالیز')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'گرید فولاد',
                'verbose_name_plural': 'گریدهای فولاد',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='LFTemperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(verbose_name='دما (°C)')),
                ('oxygen_activity', models.FloatField(blank=True, null=True, verbose_name='اکسیژن فعال (ppm)')),
                ('energy_supplied', models.FloatField(default=0, verbose_name='انرژی مصرفی (kWh/t)')),
                ('phase', models.CharField(blank=True, max_length=50, null=True, verbose_name='فاز')),
                ('measured_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان اندازه\u200cگیری')),
                ('heat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperatures', to='lf.lfheat', verbose_name='ذوب')),
            ],
            options={
                'verbose_name': 'دمای LF',
                'verbose_name_plural': 'دماهای LF',
                'ordering': ['-measured_at'],
            },
        ),
        migrations.AddField(
            model_name='lfheat',
            name='steel_grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lf.steelgrade', verbose_name='گرید فولاد'),
        ),
        migrations.CreateModel(
            name='LFDelay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('electrical', 'برقی'), ('mechanical', 'مکانیکی'), ('process', 'فرآیندی'), ('material', 'مواد'), ('maintenance', 'نگهداری')], max_length=20, verbose_name='دسته\u200cبندی')),
                ('code', models.CharField(max_length=20, verbose_name='کد توقف')),
                ('description', models.CharField(max_length=500, verbose_name='توضیحات')),
                ('cause', models.TextField(blank=True, null=True, verbose_name='علت')),
                ('start_time', models.DateTimeField(verbose_name='زمان شروع')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان')),
                ('duration', models.IntegerField(default=0, verbose_name='مدت (ثانیه)')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('completed', 'تکمیل شده')], default='active', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('heat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delays', to='lf.lfheat', verbose_name='ذوب')),
            ],
            options={
                'verbose_name': 'تأخیر LF',
                'verbose_name_plural': 'تأخیرهای LF',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='LFAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=20, verbose_name='شناسه نمونه')),
                ('c', models.FloatField(default=0, verbose_name='کربن (C%)')),
                ('mn', models.FloatField(default=0, verbose_name='منگنز (Mn%)')),
                ('si', models.FloatField(default=0, verbose_name='سیلیسیم (Si%)')),
                ('p', models.FloatField(default=0, verbose_name='فسفر (P%)')),
                ('s', models.FloatField(default=0, verbose_name='گوگرد (S%)')),
                ('cr', models.FloatField(default=0, verbose_name='کروم (Cr%)')),
                ('ni', models.FloatField(default=0, verbose_name='نیکل (Ni%)')),
                ('mo', models.FloatField(default=0, verbose_name='مولیبدن (Mo%)')),
                ('al', models.FloatField(default=0, verbose_name='آلومینیوم (Al%)')),
                ('sample_time', models.DateTimeField(verbose_name='زمان取样')),
                ('analysis_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان آنالیز')),
                ('heat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='lf.lfheat', verbose_name='ذوب')),
            ],
            options={
                'verbose_name': 'آنالیز LF',
                'verbose_name_plural': 'آنالیزهای LF',
                'ordering': ['-analysis_time'],
            },
        ),
        migrations.CreateModel(
            name='LFAddition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_code', models.CharField(max_length=50, verbose_name='کد ماده')),
                ('material_name', models.CharField(max_length=200, verbose_name='نام ماده')),
                ('standard_qty', models.FloatField(default=0, verbose_name='مقدار استاندارد (kg)')),
                ('calculated_qty', models.FloatField(default=0, verbose_name='مقدار محاسبه شده (kg)')),
                ('confirmed_qty', models.FloatField(default=0, verbose_name='مقدار تایید شده (kg)')),
                ('actual_qty', models.FloatField(default=0, verbose_name='مقدار واقعی (kg)')),
                ('unit', models.CharField(default='kg', max_length=10, verbose_name='واحد')),
                ('added_to', models.CharField(choices=[('furnace', 'کوره'), ('ladle', 'پاتیل')], default='ladle', max_length=20, verbose_name='محل افزودن')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('confirmed', 'تایید شده'), ('completed', 'انجام شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('timestamp', models.DateTimeField(blank=True, null=True, verbose_name='زمان افزودن')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تایید')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('heat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additions', to='lf.lfheat', verbose_name='ذوب')),
            ],
            options={
                'verbose_name': 'افزودنی LF',
                'verbose_name_plural': 'افزودنی\u200cهای LF',
            },
        ),
    ]
