# Generated by Django 4.2.7 on 2026-05-03 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lfaddition',
            options={'verbose_name': 'LF Addition', 'verbose_name_plural': 'LF Additions'},
        ),
        migrations.AlterModelOptions(
            name='lfanalysis',
            options={'ordering': ['-analysis_time'], 'verbose_name': 'LF Analysis', 'verbose_name_plural': 'LF Analyses'},
        ),
        migrations.AlterModelOptions(
            name='lfdelay',
            options={'ordering': ['-start_time'], 'verbose_name': 'LF Delay', 'verbose_name_plural': 'LF Delays'},
        ),
        migrations.AlterModelOptions(
            name='lfheat',
            options={'ordering': ['-heat_number'], 'verbose_name': 'LF Heat', 'verbose_name_plural': 'LF Heats'},
        ),
        migrations.AlterModelOptions(
            name='lftemperature',
            options={'ordering': ['-measured_at'], 'verbose_name': 'LF Temperature', 'verbose_name_plural': 'LF Temperatures'},
        ),
        migrations.AlterModelOptions(
            name='steelgrade',
            options={'ordering': ['code'], 'verbose_name': 'Steel Grade', 'verbose_name_plural': 'Steel Grades'},
        ),
        migrations.AddField(
            model_name='lfheat',
            name='heat_sequence',
            field=models.IntegerField(default=1, verbose_name='Heat Sequence in Order'),
        ),
        migrations.AddField(
            model_name='lfheat',
            name='temp_max',
            field=models.FloatField(default=1620, verbose_name='Maximum Temperature (°C)'),
        ),
        migrations.AddField(
            model_name='lfheat',
            name='temp_min',
            field=models.FloatField(default=1580, verbose_name='Minimum Temperature (°C)'),
        ),
        migrations.AddField(
            model_name='lfheat',
            name='temp_target',
            field=models.FloatField(default=1600, verbose_name='Target Temperature (°C)'),
        ),
        migrations.AlterField(
            model_name='lfaddition',
            name='actual_qty',
            field=models.FloatField(default=0, verbose_name='Actual Quantity (kg)'),
        ),
        migrations.AlterField(
            model_name='lfaddition',
            name='added_to',
            field=models.CharField(choices=[('furnace', 'Furnace'), ('ladle', 'Ladle')], default='ladle', max_length=20, verbose_name='Added To'),
        ),
        migrations.AlterField(
            model_name='lfaddition',
            name='calculated_qty',
            field=models.FloatField(default=0, verbose_name='Calculated Quantity (kg)'),
        ),
        migrations.AlterField(
            model_name='lfaddition',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Confirmation Time'),
        ),
        migrations.AlterField(
            model_name='lfaddition',
            name='confirmed_qty',
            field=models.FloatField(default=0, verbose_name='Confirmed Quantity (kg)'),
        ),
        migrations.AlterField(
            model_name='lfaddition',
            name='heat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additions', to='lf.lfheat', verbose_name='Heat'),
        ),
        migrations.AlterField(
            model_name='lfaddition',
            name='material_code',
            field=models.CharField(max_length=50, verbose_name='Material Code'),
        ),
        migrations.AlterField(
            model_name='lfaddition',
            name='material_name',
            field=models.CharField(max_length=200, verbose_name='Material Name'),
        ),
        migrations.AlterField(
            model_name='lfaddition',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='lfaddition',
            name='standard_qty',
            field=models.FloatField(default=0, verbose_name='Standard Quantity (kg)'),
        ),
        migrations.AlterField(
            model_name='lfaddition',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='lfaddition',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Addition Time'),
        ),
        migrations.AlterField(
            model_name='lfaddition',
            name='unit',
            field=models.CharField(default='kg', max_length=10, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='lfanalysis',
            name='al',
            field=models.FloatField(default=0, verbose_name='Aluminum (Al%)'),
        ),
        migrations.AlterField(
            model_name='lfanalysis',
            name='analysis_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Analysis Time'),
        ),
        migrations.AlterField(
            model_name='lfanalysis',
            name='c',
            field=models.FloatField(default=0, verbose_name='Carbon (C%)'),
        ),
        migrations.AlterField(
            model_name='lfanalysis',
            name='cr',
            field=models.FloatField(default=0, verbose_name='Chromium (Cr%)'),
        ),
        migrations.AlterField(
            model_name='lfanalysis',
            name='heat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='lf.lfheat', verbose_name='Heat'),
        ),
        migrations.AlterField(
            model_name='lfanalysis',
            name='mn',
            field=models.FloatField(default=0, verbose_name='Manganese (Mn%)'),
        ),
        migrations.AlterField(
            model_name='lfanalysis',
            name='mo',
            field=models.FloatField(default=0, verbose_name='Molybdenum (Mo%)'),
        ),
        migrations.AlterField(
            model_name='lfanalysis',
            name='ni',
            field=models.FloatField(default=0, verbose_name='Nickel (Ni%)'),
        ),
        migrations.AlterField(
            model_name='lfanalysis',
            name='p',
            field=models.FloatField(default=0, verbose_name='Phosphorus (P%)'),
        ),
        migrations.AlterField(
            model_name='lfanalysis',
            name='s',
            field=models.FloatField(default=0, verbose_name='Sulfur (S%)'),
        ),
        migrations.AlterField(
            model_name='lfanalysis',
            name='sample_id',
            field=models.CharField(max_length=20, verbose_name='Sample ID'),
        ),
        migrations.AlterField(
            model_name='lfanalysis',
            name='sample_time',
            field=models.DateTimeField(verbose_name='Sample Time'),
        ),
        migrations.AlterField(
            model_name='lfanalysis',
            name='si',
            field=models.FloatField(default=0, verbose_name='Silicon (Si%)'),
        ),
        migrations.AlterField(
            model_name='lfdelay',
            name='category',
            field=models.CharField(choices=[('electrical', 'Electrical'), ('mechanical', 'Mechanical'), ('process', 'Process'), ('material', 'Material'), ('maintenance', 'Maintenance')], max_length=20, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='lfdelay',
            name='cause',
            field=models.TextField(blank=True, null=True, verbose_name='Cause'),
        ),
        migrations.AlterField(
            model_name='lfdelay',
            name='code',
            field=models.CharField(max_length=20, verbose_name='Stop Code'),
        ),
        migrations.AlterField(
            model_name='lfdelay',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='lfdelay',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='Duration (seconds)'),
        ),
        migrations.AlterField(
            model_name='lfdelay',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='lfdelay',
            name='heat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delays', to='lf.lfheat', verbose_name='Heat'),
        ),
        migrations.AlterField(
            model_name='lfdelay',
            name='start_time',
            field=models.DateTimeField(verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='lfdelay',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='lfheat',
            name='argon_flow',
            field=models.FloatField(default=150, verbose_name='Argon Flow (L/min)'),
        ),
        migrations.AlterField(
            model_name='lfheat',
            name='current_phase',
            field=models.CharField(choices=[('preparation', 'Preparation'), ('ladle_arrival', 'Ladle Arrival'), ('heating', 'Heating'), ('alloying', 'Alloying'), ('trimming', 'Trimming'), ('holding', 'Holding'), ('tapping', 'Tapping')], default='preparation', max_length=20, verbose_name='Current Phase'),
        ),
        migrations.AlterField(
            model_name='lfheat',
            name='electrode_position',
            field=models.FloatField(default=450, verbose_name='Electrode Position (mm)'),
        ),
        migrations.AlterField(
            model_name='lfheat',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='lfheat',
            name='furnace_id',
            field=models.IntegerField(default=1, verbose_name='Furnace ID'),
        ),
        migrations.AlterField(
            model_name='lfheat',
            name='heat_number',
            field=models.IntegerField(unique=True, verbose_name='Heat Number'),
        ),
        migrations.AlterField(
            model_name='lfheat',
            name='heating_power',
            field=models.FloatField(default=15, verbose_name='Heating Power (MW)'),
        ),
        migrations.AlterField(
            model_name='lfheat',
            name='liquid_weight',
            field=models.FloatField(default=0, verbose_name='Liquid Weight (tons)'),
        ),
        migrations.AlterField(
            model_name='lfheat',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='lfheat',
            name='operator_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Operator Name'),
        ),
        migrations.AlterField(
            model_name='lfheat',
            name='phase_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Current Phase Start Time'),
        ),
        migrations.AlterField(
            model_name='lfheat',
            name='production_standard',
            field=models.CharField(default='LF_STD_FAST', max_length=50, verbose_name='Production Standard'),
        ),
        migrations.AlterField(
            model_name='lfheat',
            name='shift_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Shift ID'),
        ),
        migrations.AlterField(
            model_name='lfheat',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='lfheat',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('ready_to_tap', 'Ready to Tap')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='lfheat',
            name='steel_grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lf.steelgrade', verbose_name='Steel Grade'),
        ),
        migrations.AlterField(
            model_name='lfheat',
            name='target_liquid_weight',
            field=models.FloatField(default=120, verbose_name='Target Weight (tons)'),
        ),
        migrations.AlterField(
            model_name='lftemperature',
            name='energy_supplied',
            field=models.FloatField(default=0, verbose_name='Energy Supplied (kWh/t)'),
        ),
        migrations.AlterField(
            model_name='lftemperature',
            name='heat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperatures', to='lf.lfheat', verbose_name='Heat'),
        ),
        migrations.AlterField(
            model_name='lftemperature',
            name='measured_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Measurement Time'),
        ),
        migrations.AlterField(
            model_name='lftemperature',
            name='oxygen_activity',
            field=models.FloatField(blank=True, null=True, verbose_name='Oxygen Activity (ppm)'),
        ),
        migrations.AlterField(
            model_name='lftemperature',
            name='phase',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Phase'),
        ),
        migrations.AlterField(
            model_name='lftemperature',
            name='temperature',
            field=models.FloatField(verbose_name='Temperature (°C)'),
        ),
        migrations.AlterField(
            model_name='steelgrade',
            name='analysis_limits',
            field=models.JSONField(default=dict, verbose_name='Analysis Limits'),
        ),
        migrations.AlterField(
            model_name='steelgrade',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Steel Code'),
        ),
        migrations.AlterField(
            model_name='steelgrade',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='steelgrade',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='steelgrade',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Steel Name'),
        ),
        migrations.AlterField(
            model_name='steelgrade',
            name='temp_max',
            field=models.FloatField(default=1620, verbose_name='Maximum Temperature (°C)'),
        ),
        migrations.AlterField(
            model_name='steelgrade',
            name='temp_min',
            field=models.FloatField(default=1570, verbose_name='Minimum Temperature (°C)'),
        ),
        migrations.AlterField(
            model_name='steelgrade',
            name='temp_target',
            field=models.FloatField(default=1600, verbose_name='Target Temperature (°C)'),
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='Order Number')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Customer Name')),
                ('customer_po', models.CharField(blank=True, max_length=100, null=True, verbose_name='Customer PO Number')),
                ('product_description', models.TextField(blank=True, verbose_name='Product Description')),
                ('quantity_tons', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Quantity (tons)')),
                ('quantity_heats', models.IntegerField(default=1, verbose_name='Number of Heats')),
                ('required_by_date', models.DateField(blank=True, null=True, verbose_name='Required By Date')),
                ('temp_target', models.IntegerField(default=1600, verbose_name='Target Temperature (°C)')),
                ('temp_min', models.IntegerField(default=1580, verbose_name='Minimum Temperature (°C)')),
                ('temp_max', models.IntegerField(default=1620, verbose_name='Maximum Temperature (°C)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Order Status')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10, verbose_name='Priority')),
                ('planned_start_date', models.DateTimeField(blank=True, null=True, verbose_name='Planned Start Date')),
                ('actual_start_date', models.DateTimeField(blank=True, null=True, verbose_name='Actual Start Date')),
                ('actual_end_date', models.DateTimeField(blank=True, null=True, verbose_name='Actual End Date')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='Attachments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('steel_grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='lf.steelgrade', verbose_name='Steel Grade')),
            ],
            options={
                'verbose_name': 'Production Order',
                'verbose_name_plural': 'Production Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='lfheat',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='heats', to='lf.productionorder', verbose_name='Production Order'),
        ),
        migrations.AlterUniqueTogether(
            name='lfheat',
            unique_together={('order', 'heat_sequence')},
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['order_number'], name='lf_producti_order_n_1d2abd_idx'),
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['status'], name='lf_producti_status_1c8dec_idx'),
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['priority'], name='lf_producti_priorit_2b388d_idx'),
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['required_by_date'], name='lf_producti_require_aa0086_idx'),
        ),
    ]
