# Generated by Django 4.2.7 on 2026-05-03 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lf', '0002_alter_lfaddition_options_alter_lfanalysis_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lfheat',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='lfheat',
            name='heat_sequence',
        ),
        migrations.RemoveField(
            model_name='lfheat',
            name='order',
        ),
        migrations.RemoveField(
            model_name='lfheat',
            name='temp_max',
        ),
        migrations.RemoveField(
            model_name='lfheat',
            name='temp_min',
        ),
        migrations.RemoveField(
            model_name='lfheat',
            name='temp_target',
        ),
        migrations.DeleteModel(
            name='ProductionOrder',
        ),
    ]
