# Generated by Django 4.2.7 on 2026-05-05 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_delete_orderheat'),
        ('lf', '0003_alter_lfheat_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lfheat',
            name='bucket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heats', to='production.productionbucket', verbose_name='Production Bucket'),
        ),
        migrations.AddField(
            model_name='lfheat',
            name='heat_sequence',
            field=models.IntegerField(default=1, verbose_name='Heat Sequence in Bucket'),
        ),
        migrations.AddField(
            model_name='lfheat',
            name='temp_max',
            field=models.FloatField(default=1620, verbose_name='Maximum Temperature (°C)'),
        ),
        migrations.AddField(
            model_name='lfheat',
            name='temp_min',
            field=models.FloatField(default=1580, verbose_name='Minimum Temperature (°C)'),
        ),
        migrations.AddField(
            model_name='lfheat',
            name='temp_target',
            field=models.FloatField(default=1600, verbose_name='Target Temperature (°C)'),
        ),
        migrations.AddIndex(
            model_name='lfheat',
            index=models.Index(fields=['bucket', 'heat_sequence'], name='lf_lfheat_bucket__93563a_idx'),
        ),
        migrations.AddIndex(
            model_name='lfheat',
            index=models.Index(fields=['status'], name='lf_lfheat_status_f88e1c_idx'),
        ),
        migrations.AddIndex(
            model_name='lfheat',
            index=models.Index(fields=['current_phase'], name='lf_lfheat_current_d84e01_idx'),
        ),
    ]
