# Generated by Django 4.2.7 on 2026-05-04 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lf', '0003_alter_lfheat_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='Order Number')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Customer Name')),
                ('customer_po', models.CharField(blank=True, max_length=100, null=True, verbose_name='Customer PO Number')),
                ('product_description', models.TextField(blank=True, verbose_name='Product Description')),
                ('quantity_tons', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Quantity (tons)')),
                ('quantity_heats', models.IntegerField(default=1, verbose_name='Number of Heats')),
                ('required_by_date', models.DateField(blank=True, null=True, verbose_name='Required By Date')),
                ('temp_target', models.IntegerField(default=1600, verbose_name='Target Temperature (°C)')),
                ('temp_min', models.IntegerField(default=1580, verbose_name='Minimum Temperature (°C)')),
                ('temp_max', models.IntegerField(default=1620, verbose_name='Maximum Temperature (°C)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Order Status')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10, verbose_name='Priority')),
                ('planned_start_date', models.DateTimeField(blank=True, null=True, verbose_name='Planned Start Date')),
                ('actual_start_date', models.DateTimeField(blank=True, null=True, verbose_name='Actual Start Date')),
                ('actual_end_date', models.DateTimeField(blank=True, null=True, verbose_name='Actual End Date')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='Attachments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('steel_grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='lf.steelgrade', verbose_name='Steel Grade')),
            ],
            options={
                'verbose_name': 'Production Order',
                'verbose_name_plural': 'Production Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_number', models.CharField(max_length=50, verbose_name='Bucket Number')),
                ('bucket_sequence', models.IntegerField(default=1, verbose_name='Bucket Sequence')),
                ('planned_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Planned Quantity (tons)')),
                ('actual_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Actual Quantity (tons)')),
                ('planned_start_date', models.DateTimeField(blank=True, null=True, verbose_name='Planned Start Date')),
                ('planned_end_date', models.DateTimeField(blank=True, null=True, verbose_name='Planned End Date')),
                ('actual_start_date', models.DateTimeField(blank=True, null=True, verbose_name='Actual Start Date')),
                ('actual_end_date', models.DateTimeField(blank=True, null=True, verbose_name='Actual End Date')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20, verbose_name='Bucket Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buckets', to='production.productionorder', verbose_name='Production Order')),
            ],
            options={
                'verbose_name': 'Production Bucket',
                'verbose_name_plural': 'Production Buckets',
                'ordering': ['bucket_sequence'],
            },
        ),
        migrations.CreateModel(
            name='OrderHeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heat_sequence', models.IntegerField(verbose_name='Heat Sequence in Bucket')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bucket_heats', to='production.productionbucket')),
                ('heat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_heat', to='lf.lfheat')),
            ],
            options={
                'verbose_name': 'Order Heat',
                'verbose_name_plural': 'Order Heats',
                'ordering': ['heat_sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['order_number'], name='production__order_n_6086ee_idx'),
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['status'], name='production__status_b4dbe1_idx'),
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['priority'], name='production__priorit_e2ad8d_idx'),
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['required_by_date'], name='production__require_dfee0b_idx'),
        ),
        migrations.AddIndex(
            model_name='productionbucket',
            index=models.Index(fields=['order', 'bucket_number'], name='production__order_i_4d9892_idx'),
        ),
        migrations.AddIndex(
            model_name='productionbucket',
            index=models.Index(fields=['status'], name='production__status_35e11b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productionbucket',
            unique_together={('order', 'bucket_number')},
        ),
        migrations.AlterUniqueTogether(
            name='orderheat',
            unique_together={('bucket', 'heat_sequence')},
        ),
    ]
