# Generated by Django 4.2.7 on 2026-05-05 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderHeat',
        ),
    ]
